services:
  db:
    image: bitnami/postgresql:16.2.0
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: person
      POSTGRESQL_TIMEZONE: "UTC"
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    ports:
      - 8082:8080
    volumes:
      - ./config/keycloak/import:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin