server:
  port: 8080
spring:
  application:
    name: individuals-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: ${keycloak.clientId}
keycloak:
  realm: merchants
  domain: localhost:9005
  clientId: merchants-manager
  clientSecret: 1C6AlBQedQnAmOPVD9TDjyKPLK163LP7
  urls:
    auth: http://${keycloak.domain}
url-frontend-guest: http://localhost
