server:
  port: 8088
spring:
  application:
    name: individuals-api
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: merchantsclient
            client-secret: aQe2UelkaeGNnAUA8JV7p8Lnhdw03wqm
            provider: keycloak
            scope: openid, profile, email, roles, microprofile-jwt
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/merchantsrealm
            user-name-attribute: preferred_username
keycloak:
  server-url: http://localhost:8082
  realm: merchantsrealm
  username: admin
  password: admin
logging:
  level:
    root: debug